### ISSUE TITLE
jar not available via maven central

### ISSUE THREAD

**Issue by samsach** [awslabs/amazon-kinesis-connectors#23]
Would be nice if we had the jarfile for this on maven central (sans samples).

**Comment by oli99sc** [comment]
I also would like to see your library within maven central.

**Comment by sarxos** [comment]
Hi @awslabs team!

Thank you for the great piece of code. Is there any progress in deploying this to Maven Central? We would love to have it available there.

**Comment by alexconlin** [comment]
I would also like to be able to see this published to maven central :+1:

**Comment by darkcrawler01** [comment]
@awslabs : any updates on the maven status ?

Until then can anyone share their pom file if they have written one to build it as a jar?

**Comment by alexconlin** [comment]
Here's mine: https://s3-eu-west-1.amazonaws.com/alexgrabyo/aVEN729dnHk/kinesis-connectors-0.0.1.pom

**Comment by xflin** [comment]
Just found out that amazon-kinesis-connectors 1.1.1 is available from maven central.

**Comment by darkcrawler01** [comment]
@xflin : we are looking for a jar for this project i.e amazon-kinesis-connectors.
@alexconlin : thanks for sharing the pom.xml but i would suggest a small change to exclude src/main/samples/*

**Comment by alexconlin** [comment]
Yeah it's up there now:
http://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Camazon-kinesis-connectors%7C1.1.1%7Cjar

**Comment by manango** [comment]
amazon-kinesis-connectors 1.1.2 is also available in maven now:
http://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Camazon-kinesis-connectors%7C1.1.2%7Cjar
