### ISSUE TITLE
Getting below error when i try to run dynamodb sample.

### ISSUE THREAD

**Issue by hari571** [awslabs/amazon-kinesis-connectors#28]
Getting below error when i try to run dynamodb sample. Thanks in advance. 

ava] INFO: Created new shardConsumer for shardId: shardId-000000000000, concurrencyToken: 800bb2cc-1a82-46b9-8ec8-f5d6287c9a69
     [java] Nov 25, 2014 4:18:13 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.BlockOnParentShardTask call
     [java] INFO: No need to block on parents [] of shard shardId-000000000000
     [java] Nov 25, 2014 4:18:13 PM com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable publishMetrics
     [java] INFO: Successfully published 20 datums.
     [java] Nov 25, 2014 4:18:14 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher initialize
     [java] INFO: Initializing shard shardId-000000000000 with TRIM_HORIZON
     [java] Nov 25, 2014 4:18:14 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher initialize
     [java] INFO: Initializing shard shardId-000000000001 with TRIM_HORIZON
     [java] Nov 25, 2014 4:18:16 PM com.amazonaws.services.kinesis.connectors.dynamodb.DynamoDBEmitter performBatchRequest
     [java] SEVERE: Amazon DynamoDB Client could not perform batch request
     [java] com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: PCQTJ5602VPM99LCCU7EHGUUFFVV4KQNSO5AEMVJF66Q9ASUAAJG)
     [java]     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
     [java]     at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
     [java]     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
     [java]     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
     [java]     at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3106)
     [java]     at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.batchWriteItem(AmazonDynamoDBClient.java:771)
     [java]     at com.amazonaws.services.kinesis.connectors.dynamodb.DynamoDBEmitter.performBatchRequest(Unknown Source)
     [java]     at com.amazonaws.services.kinesis.connectors.dynamodb.DynamoDBEmitter.emit(Unknown Source)
     [java]     at com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor.emit(Unknown Source)
     [java]     at com.amazonaws.services.kinesis.connectors.KinesisConnectorRecordProcessor.processRecords(Unknown Source)
     [java]     at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ProcessTask.call(ProcessTask.java:125)
     [java]     at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:48)
     [java]     at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:23)
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java]     at java.lang.Thread.run(Thread.java:744)

**Comment by venkatwilliams** [comment]
> Is the dynamodb resource available that you are emitting to? Did you check?

Where do we check whether dynamodb resource available or not..

**Comment by venkatwilliams** [comment]
I am trying to access dynamoDB from Spark-shell using https://github.com/audienceproject/spark-dynamodb

import com.audienceproject.spark.dynamodb.implicits._

// Load a DataFrame from a Dynamo table. Only incurs the cost of a single scan for schema inference.
val dynamoDf = spark.read.dynamodb("SomeTableName")
