### ISSUE TITLE
 /third-party does not exist. BUILD FAILED

### ISSUE THREAD

**Issue by shenzhun** [awslabs/amazon-kinesis-connectors#30]
hadoop@ip-10-102-180-39:/mnt/streamingtest/amazon-kinesis-connectors/src/main$ ant -buildfile samples/s3/build.xml
Buildfile: /mnt/streamingtest/amazon-kinesis-connectors/src/main/samples/s3/build.xml

run:
    [mkdir] Created dir: /mnt/streamingtest/amazon-kinesis-connectors/src/main/build
    [javac] /mnt/streamingtest/amazon-kinesis-connectors/src/main/samples/s3/build.xml:45: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 56 source files to /mnt/streamingtest/amazon-kinesis-connectors/src/main/build

BUILD FAILED
/mnt/streamingtest/amazon-kinesis-connectors/src/main/samples/s3/build.xml:45: /third-party does not exist.

Total time: 0 seconds

**Comment by kevinmeredith** [comment]
@molgur - I had the same problem as @shenzhun.

Running ```ant setup``` *before* running ```ant run``` resolved this issue for me.

**Comment by edjames** [comment]
Just found this, which also resolved the same issue for me.
Can I suggest adding this to the README please.

**Comment by manango** [comment]
@edjames, thanks for the suggestion. We have added this information in the README.
