### ISSUE TITLE
Uncertain How to Use `redshiftbasic` Exaple

### ISSUE THREAD

**Issue by kevinmeredith** [awslabs/amazon-kinesis-connectors#33]
I'd like to use the ```redshiftbasic``` example in order to hook up my Kinesis Stream to dump into Redshift: 

* either every N minutes
* when the bucket fills up to N bytes
* etc.

It looks like, per the docs, that using the ```redshiftbasic``` example is the way to go.

However, I'm not sure how to use this code.

Do I simply need to take the children of the folder, *amazon-kinesis-connectors/src/main/samples/redshiftbasic*? Then, I need to modify a few of the source files, such as ```KinesisMessageModelRedshiftTransformer.java```, to match my data-set?

When I run the build script via ```ant```, do I run it once and then the Kinesis stream is wired up to always talk to Redshift?

Or does the program run continuously? If it stops (let's say due to ```CNTRL``` + ```Z```, do I no longer get the functionality of Kinesis dumping into Redshift?

Also - how do I compile this project? Thanks

**Comment by buzzstop03** [comment]
Looks like this is resolved from you latests posts?

**Comment by manango** [comment]
Based on #35, seems like this is resolved.
