### ISSUE TITLE
Cut 1.2.0 and host on Maven Central

### ISSUE THREAD

**Issue by alexanderdean** [awslabs/amazon-kinesis-connectors#48]
Would be great to get a latest version with all the latest fixes available on Maven Central so we can stop using our fork!

**Comment by uniuser** [comment]
version 1.1.2 is already available on maven central: http://search.maven.org/#search%7Cga%7C1%7Camazon-kinesis-connectors
is there any way to solve issue #1675, now that it is not blocked by this one?

**Comment by alexanderdean** [comment]
Awesome, this is done - closing
