### ISSUE TITLE
Script is still using default values even after modifying the properties file

### ISSUE THREAD

**Issue by loweehahn** [awslabs/amazon-kinesis-connectors#83]
The script will always run with default values even after I edited the properties file. I edited **samples/target/classes/RedshiftBasicSample.properties** and ran the **samples/target/appassembler/bin/redshift-basic-sample** but yet the stream name for example doesn't change. I also tried renaming the other properties files and executable script files but the result is still the same. I'm baffled. Can anyone advise?

**Comment by pfifer** [comment]
It's best not to make changes to files in the target directory.  The directory is management by maven.  The reason changing something in the classes directory doesn't work is that Appassembler, which generates the script, also creates a repository of the necessary jars.  This includes the jar generated by the samples project.  

The best way to change the properties file is to make the change in [src/main/resources/RedshiftBasicSample.properties](https://github.com/awslabs/amazon-kinesis-connectors/blob/master/samples/src/main/resources/RedshiftBasicSample.properties), and recompile.  This will create a new jar of the samples project and place it in the Appassembler repo.

**Comment by loweehahn** [comment]
Many thanks. I didn't know I had to recompile. Your advice has resolved my issue.
